<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contacts</name>
   <tag></tag>
   <elementGuidId>10a4fb8f-b8a3-4397-9f1f-1df0c7fe8a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sitemap-entity-NewSubArea_e3434638']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sitemap-entity-NewSubArea_e3434638 > div.pa-a.pa-av.pa-hb.pa-jn.pa-fd.pa-x.pa-lj.pa-mt.pa-mu.pa-mv.pa-mw.pa-mx.pa-my.pa-mz.pa-nt.pa-nu.flexbox > div.pa-a.pa-ku.pa-jy.pa-x.pa-f.pa-p.pa-cm.pa-kh.flexbox > div.pa-ej.pa-e.pa-p.pa-nj.flexbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Contacts&quot;i >> div >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>188d40ab-b7cc-41d6-829b-4a4bab838622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d55c8145-4f31-4bff-b60f-915333722a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ej pa-e pa-p pa-nj flexbox</value>
      <webElementGuid>5ce9164d-e3a5-4622-b1ad-3776968adcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacts</value>
      <webElementGuid>2ab2cdb7-2ec8-4150-9f66-d65eeaa37564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitemap-entity-NewSubArea_e3434638&quot;)/div[@class=&quot;pa-a pa-av pa-hb pa-jn pa-fd pa-x pa-lj pa-mt pa-mu pa-mv pa-mw pa-mx pa-my pa-mz pa-nt pa-nu flexbox&quot;]/div[@class=&quot;pa-a pa-ku pa-jy pa-x pa-f pa-p pa-cm pa-kh flexbox&quot;]/div[@class=&quot;pa-ej pa-e pa-p pa-nj flexbox&quot;]</value>
      <webElementGuid>ae62fada-e7df-4446-8c4b-b4a45d0b5ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sitemap-entity-NewSubArea_e3434638']/div/div/div[2]</value>
      <webElementGuid>7d840533-9822-447f-b47a-ed91dc5b835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::div[4]</value>
      <webElementGuid>55454836-c346-49fd-8eaf-aa8ce1d7d3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Applications'])[1]/preceding::div[2]</value>
      <webElementGuid>f7c11550-61b0-46bc-8afa-77c8693b0fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/div/div/div[2]</value>
      <webElementGuid>f6b2995c-d42e-419e-abf3-fbe3cbe4678d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contacts' or . = 'Contacts')]</value>
      <webElementGuid>fe32fbe3-aa04-45a8-8b2e-6e76985ef2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
