<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Show Chart_pa-gr pa-em pa-fd pa-en pa-gz</name>
   <tag></tag>
   <elementGuidId>5c016567-1ac9-4e40-9287-255fb5dc9a4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='account|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.account.NewRecord210-button']/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9e163d90-ca59-4354-a5a3-9528b0e0989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://content.powerapps.com/resource/uci-infra-bus/resources/images/Add.e3b9b5bbf4470fff2278314b571d3441.svg</value>
      <webElementGuid>4ca47332-5a86-4b17-9d41-c2179a9c3e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>957b5e54-27a8-4b63-87dd-d8f95ad7e116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>ba6a017c-8479-4291-a387-a9064b50e3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-gr pa-em pa-fd pa-en pa-gz </value>
      <webElementGuid>cd369078-4e29-4b23-88fc-331b7132af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.account.NewRecord210-button&quot;)/span[@class=&quot;pa-ej pa-av pa-a pa-ek&quot;]/span[@class=&quot;pa-gx pa-bz pa-gs pa-gy pa-fd pa-a pa-p pa-v pa-el&quot;]/img[@class=&quot;pa-gr pa-em pa-fd pa-en pa-gz&quot;]</value>
      <webElementGuid>95b64c91-9705-4c2e-a361-cf5fe6b36911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='account|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.account.NewRecord210-button']/span/span/img</value>
      <webElementGuid>857f89fa-b4e0-4070-8f98-6b4cb97e0535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='New']</value>
      <webElementGuid>1208e93a-2f18-42fa-b98d-73da649d9416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/span/span/img</value>
      <webElementGuid>8718da84-a59a-44b6-ad20-1bc82c775392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://content.powerapps.com/resource/uci-infra-bus/resources/images/Add.e3b9b5bbf4470fff2278314b571d3441.svg' and @alt = 'New' and @title = 'New']</value>
      <webElementGuid>8acb393d-e240-4190-b7f9-796916355e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
