<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name Arabic_id-a72c7955-442b-_8ac201</name>
   <tag></tag>
   <elementGuidId>8bd5aac2-8df5-42f7-8ed9-a57cd9761067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company Name Arabic&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ccfe32f-1ef6-41c1-9f21-209e6eed831f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-text</value>
      <webElementGuid>46ba6314-34cd-4773-b1de-8d894abbbde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company Name Arabic</value>
      <webElementGuid>88dfaec5-63e1-48c5-b554-b43255397ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cd346d0-f456-49fa-b095-885f2a720d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>ldv_companynamearabic.fieldControl-text-box-text</value>
      <webElementGuid>53c70346-0f2a-4dee-9c08-ee9e27564075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e51ad718-d3f6-4a7f-9cf0-f839d91614ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5600322-d249-45d5-8152-f65f6d15d9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef1b81ef-d987-4746-93d9-89c4416231a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-z pa-kj pa-rr pa-av pa-cq pa-bz pa-wy pa-l pa-iu pa-by pa-rv pa-uc pa-as pa-at pa-eu pa-ge pa-er pa-km pa-yy pa-yz pa-kp pa-za pa-kq </value>
      <webElementGuid>d02b27ac-8728-4056-805b-7a4aa0f6e3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75b3ba9a-67a0-46de-8c21-0a7ed02b50f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>946d274f-62eb-4108-8f4a-3dd520375ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-text']</value>
      <webElementGuid>a91eaec5-7102-4c25-9e1f-b32c718b8ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-container']/input</value>
      <webElementGuid>a722b699-b4ce-42f3-854c-99a4ebd7c970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>be3bab17-a8ad-4558-9e88-d1b3bb29c8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-a72c7955-442b-4ea4-9499-b10cd18b4256-2-ldv_companynamearabic4273edbd-ac1d-40d3-9fb2-095c621b552d-ldv_companynamearabic.fieldControl-text-box-text' and @type = 'text']</value>
      <webElementGuid>6bb77b22-893a-4eb5-b5ea-8f39b449c446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
