<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_id-cc760212-3eab-4009-b5c3-ea9c_a4b1a0</name>
   <tag></tag>
   <elementGuidId>95297395-ae31-4a0a-907d-ca53bda1901a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Provide an email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e3ebdef-30e8-4155-a870-5da176e987e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input</value>
      <webElementGuid>1ec1951c-19e1-42b2-ba66-6b43e4196881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>d63b4f17-8693-414c-95b0-eaa11f4f3d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a4ae62c-1544-4d82-8f22-e5952769af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>emailaddress1.fieldControl-mail-text-input</value>
      <webElementGuid>0b0f9afb-09cc-48c5-91d1-77bde02dc8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Provide an email</value>
      <webElementGuid>2f5967ac-5bb0-4e33-88b7-ff98d97a60fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b75d1d2b-5740-45a8-88df-b8e5aca052a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85fec657-8387-4b34-a78a-00684322fb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-z pa-kq pa-ro pa-av pa-cl pa-bz pa-ww pa-l pa-iu pa-by pa-rs pa-uc pa-as pa-at pa-eu pa-he pa-er pa-kt pa-zb pa-zc pa-kw pa-zd pa-kx </value>
      <webElementGuid>098c892f-4fc6-4b33-a1f2-5bd05a8d846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2789996-82e2-45d6-974d-e8765dc95e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input&quot;)</value>
      <webElementGuid>fd28f88d-823e-4c6e-aa1a-119ea456657b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input']</value>
      <webElementGuid>b3942777-976d-4763-872c-22c23b69be00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-container']/input</value>
      <webElementGuid>e117aa81-2f25-46f5-8385-b65472256b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>c214bbbc-78a5-4f2b-b405-86b87244a833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input' and @placeholder = 'Provide an email' and @type = 'text']</value>
      <webElementGuid>5b230dda-165f-42b6-8674-1aa758124e64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
