<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_iti__tel-input</name>
   <tag></tag>
   <elementGuidId>9b3fb80e-498f-43ac-97cd-c7ac17b0ed0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.iti__tel-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#id-1212_11 >> internal:attr=[placeholder=&quot;50 123 4567&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1807d6a-2585-4a00-88bf-d2d02a0f67b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d6a8be28-b7fc-4321-a24d-98bfa9fe3990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__tel-input</value>
      <webElementGuid>a0907617-5458-4180-b3a2-d3f60327a14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>50 123 4567</value>
      <webElementGuid>c2605c94-b94d-4f12-8d5d-0c892e8ef750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3683d415-7c44-4832-948f-35d08237b37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c5a79d0-61a9-43bf-8201-73782c4809c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6db8d996-b63a-49de-acaa-835a1eadb1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-7-mobilephonef9a8a302-114e-466a-b582-6771b2ae0d92-mobilephone.fieldControl-pcf-container-id&quot;)/div[@id=&quot;linkdev-IntTelInput&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--show-selected-dial-code iti--show-flags iti--inline-dropdown&quot;]/input[@class=&quot;iti__tel-input&quot;]</value>
      <webElementGuid>2a8561b4-b960-46ae-9c09-f56a9a546016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>9727f996-7b40-4ea9-9eb7-dc0fab715a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkdev-IntTelInput']/div/input</value>
      <webElementGuid>6e822f3c-193c-47dd-91b0-6988b2f8701e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>4bb45c9e-65e0-43b9-8576-2fe0652be3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '50 123 4567']</value>
      <webElementGuid>a530d704-a038-46ad-9939-222f74f79566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
