<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_id-cc760212-3eab-4009-b5c3-_d15241</name>
   <tag></tag>
   <elementGuidId>f379838d-d14f-4c0f-951b-9d6fb4a3e387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>852a713a-aed2-40ef-b48e-fea1deb4c2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text</value>
      <webElementGuid>7758135a-4598-4a13-ac52-a42b9953e54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>8ce5964e-8ba2-4218-a42d-9a89f3f7bbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddd0b619-fe93-4d6c-a825-d95f3a7519dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>lastname.fieldControl-text-box-text</value>
      <webElementGuid>81f18e13-7557-48e5-902e-beff6c4ecf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9cd659b2-643d-41f7-aeca-1b51cf0e3cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc660ce1-b154-4fee-9821-32fe7cf418bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b4e2823-5010-45ab-905f-3eaacb6f490b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-z pa-kq pa-ro pa-av pa-cl pa-bz pa-ww pa-l pa-iu pa-by pa-rs pa-uc pa-as pa-at pa-eu pa-he pa-er pa-kt pa-zb pa-zc pa-kw pa-zd pa-kx </value>
      <webElementGuid>98823f6b-648e-4472-9325-b7a3069b103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>532b1589-37bd-4e07-ae47-271f451f174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>cb2070f7-d0d4-486f-91f2-5a1d4b91c4d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text']</value>
      <webElementGuid>fa09e51c-2709-4def-b377-56691391b96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-container']/input</value>
      <webElementGuid>4f5a70b3-4cdf-4a7d-9e02-cf8563a37ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>b878bcad-de8a-4f73-88fc-265cc3196a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-2-lastname4273edbd-ac1d-40d3-9fb2-095c621b552d-lastname.fieldControl-text-box-text' and @type = 'text']</value>
      <webElementGuid>92ad6ead-f92b-497b-8479-a26d43318eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
