<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name English_id-a72c7955-442b_084296</name>
   <tag></tag>
   <elementGuidId>31222222-554a-498b-a277-4384d11d0b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Company Name English&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>499eb7bf-f75c-46ac-9bb5-593836d5856b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-text</value>
      <webElementGuid>53160bf6-d978-46e9-900f-265097149daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company Name English</value>
      <webElementGuid>a00f8ba0-de0a-4df2-b8f4-fe81333b50a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>028b1e26-77c8-4291-838a-877bc1d9aec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>name.fieldControl-text-box-text</value>
      <webElementGuid>46fc3e05-40bc-4026-a2fb-b5264eb1ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>771b85be-9705-4451-83cc-b7d570b32d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72e0548e-0477-4569-8350-830ca12b920e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63c49397-b467-4c9a-87ab-1fc73c2695af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-z pa-kj pa-rr pa-av pa-cq pa-bz pa-qh pa-zb pa-iu pa-by pa-rv pa-uc pa-as pa-at pa-eu pa-zc pa-er pa-zl pa-yy pa-yz pa-kp pa-za pa-kq </value>
      <webElementGuid>2f222435-7978-4476-ac7d-a73834d4f88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name-error-message</value>
      <webElementGuid>bcb9175b-a60f-4153-8500-ddec51781b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14309ed3-22f4-4dfd-9c9e-2b0863d92fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-text&quot;)</value>
      <webElementGuid>e5a4b1d2-eb4d-44d9-b3ef-32614c48a54a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-text']</value>
      <webElementGuid>2d8d49f8-b202-48f5-ad79-476eb23d13cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-container']/input</value>
      <webElementGuid>20ce3a58-f5c1-478c-b8b7-92a5ee26a715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>ad80fef2-245f-45fa-9e4d-99b5b98870f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-a72c7955-442b-4ea4-9499-b10cd18b4256-1-name4273edbd-ac1d-40d3-9fb2-095c621b552d-name.fieldControl-text-box-text' and @type = 'text']</value>
      <webElementGuid>cb5a33a9-90d3-428e-827d-2d0ff5fb5df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
