<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EventsMeetingsCall Center</name>
   <tag></tag>
   <elementGuidId>93f997e5-d027-4d72-9d31-70836ffbbc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Source&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1ca18f6-01cd-499b-9270-d8e84ed58848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select</value>
      <webElementGuid>cae6e78c-13c6-4e22-9654-fecff04e679b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Source</value>
      <webElementGuid>a11bc107-060f-43d0-9787-1d8d3b437ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74f77329-113e-4932-96b1-c2a956b6aec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>42ede210-84ea-42cc-9dbc-012609ea680d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>ldv_sourcecode.fieldControl-option-set-select</value>
      <webElementGuid>6842a0f6-be39-451e-96d3-7481b3617efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ya pa-f pa-av pa-yb pa-yc pa-yd pa-bz pa-ww pa-bd pa-er pa-l pa-ye pa-yk pa-yh pa-yi pa-yj </value>
      <webElementGuid>3003135a-8a61-4f11-84b2-4dc746732890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>969d2d35-e104-46aa-bc8f-17e2318afb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--EventsMeetingsCall Center</value>
      <webElementGuid>c20ca131-320b-45e7-8482-2b2689bd2265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select&quot;)</value>
      <webElementGuid>396efdee-590e-4d08-a97e-497033d01a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select']</value>
      <webElementGuid>9425d255-db19-4292-a052-89f480b720b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select-container']/select</value>
      <webElementGuid>3be4d77f-7fef-4261-b725-ad7a3dc71fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/following::select[1]</value>
      <webElementGuid>4f6eb3cb-a1a1-4b61-848c-769de21b71a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[2]/following::select[2]</value>
      <webElementGuid>7324f281-ccd5-4db1-ba16-457e30409cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Details'])[1]/preceding::select[1]</value>
      <webElementGuid>1692131f-2d8a-43f6-9609-ed1efd16516f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[1]</value>
      <webElementGuid>2bf2c62c-1d6a-4bb4-8921-f7e7b75c63f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>02a5821d-9738-4672-b0f8-7b8bcdf3a215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id-cc760212-3eab-4009-b5c3-ea9cf6f3e141-4-ldv_sourcecode3ef39988-22bb-4f0b-bbbe-64b5a3748aee-ldv_sourcecode.fieldControl-option-set-select' and @title = '--Select--' and (text() = '--Select--EventsMeetingsCall Center' or . = '--Select--EventsMeetingsCall Center')]</value>
      <webElementGuid>362f523f-68aa-486f-bdd9-af55c6162ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
