<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New</name>
   <tag></tag>
   <elementGuidId>17b91fae-2190-4ff4-a503-d7558dd9ceeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='contact|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.contact.NewRecord210-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc02f39b-0044-46cb-b362-eefea0f1aa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f49b1d9-8aca-457d-8078-c9fdef300a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ej pa-av pa-a pa-ek </value>
      <webElementGuid>9a9f67ee-9b40-4df8-96f7-f5d7a10daa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>ca593aad-63b7-44af-82d2-40653635e147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.contact.NewRecord210-button&quot;)/span[@class=&quot;pa-ej pa-av pa-a pa-ek&quot;]</value>
      <webElementGuid>5d4c2f53-1dfb-4e58-a10d-e0cf9a5739f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='contact|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.contact.NewRecord210-button']/span</value>
      <webElementGuid>db5793d0-719a-4961-b913-39e4f5ea1f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Chart'])[1]/following::span[1]</value>
      <webElementGuid>87184c4a-0743-4367-8002-a5667b23d482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Focused view'])[1]/following::span[4]</value>
      <webElementGuid>77e9823e-2e3a-4eb7-8162-ebb74737a76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a new Contact record.'])[1]/preceding::span[3]</value>
      <webElementGuid>4fe68fd2-4db4-4cd8-bc1e-788a993b07b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/ul/li[3]/button/span</value>
      <webElementGuid>70a3ddc6-cbb8-43b1-aa4e-5c363fa534a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'New' or . = 'New')]</value>
      <webElementGuid>2422e758-9f1f-436a-924c-de0d21436097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
