<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Companies</name>
   <tag></tag>
   <elementGuidId>823eb79b-7b7a-4eed-9f72-2bb8e0f4dbdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sitemap-entity-NewSubArea_ed4af58a']/div/div/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sitemap-entity-NewSubArea_ed4af58a > div.pa-a.pa-av.pa-gb.pa-jn.pa-fd.pa-x.pa-lj.pa-pn.pa-po.pa-pp.pa-pq.pa-pr.pa-ps.pa-pt.pa-ql.pa-qm.flexbox > div.pa-a.pa-kn.pa-kr.pa-x.pa-f.pa-p.pa-cr.pa-ka.flexbox > div.pa-ej.pa-e.pa-p.pa-qc.flexbox > span.pa-hq.pa-p.pa-qd.pa-gq.pa-gf.pa-gu.pa-ao.pa-cr.pa-cq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Companies&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ac31ee7-e8cf-495d-aee7-d0d19c777922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-hq pa-p pa-qd pa-gq pa-gf pa-gu pa-ao pa-cr pa-cq </value>
      <webElementGuid>c5030cd1-534c-456e-97e3-72ab3051d6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Companies</value>
      <webElementGuid>920e9495-053e-43c7-8f9b-ea7a2084b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitemap-entity-NewSubArea_ed4af58a&quot;)/div[@class=&quot;pa-a pa-av pa-gb pa-jn pa-fd pa-x pa-lj pa-pn pa-po pa-pp pa-pq pa-pr pa-ps pa-pt pa-ql pa-qm flexbox&quot;]/div[@class=&quot;pa-a pa-kn pa-kr pa-x pa-f pa-p pa-cr pa-ka flexbox&quot;]/div[@class=&quot;pa-ej pa-e pa-p pa-qc flexbox&quot;]/span[@class=&quot;pa-hq pa-p pa-qd pa-gq pa-gf pa-gu pa-ao pa-cr pa-cq&quot;]</value>
      <webElementGuid>cc640340-7d68-4f98-840f-c8d4d29e42a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sitemap-entity-NewSubArea_ed4af58a']/div/div/div[2]/span[2]</value>
      <webElementGuid>54404cbe-b920-4b68-95b2-75d8ec76cc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Setup Companies'])[1]/following::span[2]</value>
      <webElementGuid>a6b66037-b4a5-417c-91c8-36a86e43dba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[2]</value>
      <webElementGuid>3b062b86-d940-4c4b-a4c2-5c45462ea009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Applications'])[1]/preceding::span[4]</value>
      <webElementGuid>f7eb5774-23cb-4a00-8e90-82f80f345b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Companies']/parent::*</value>
      <webElementGuid>31911690-8a02-475f-992d-e373a0787c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/div/div/div[2]/span[2]</value>
      <webElementGuid>dce276de-2a34-4b7a-a1bc-9c5a13db63d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Companies' or . = 'Companies')]</value>
      <webElementGuid>8786beb0-2f9c-4078-9d8e-18aecf5a0f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
