<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send feedback to Microsoft_symbolFont _16d4bd</name>
   <tag></tag>
   <elementGuidId>b7ba3aed-62b4-454b-9ed2-d62845a34621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-1']/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.symbolFont.SiteMap-symbol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Site Map&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9e7e21c-44d7-412e-84bf-4793edff64c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbolFont SiteMap-symbol  </value>
      <webElementGuid>82630206-6822-45ca-a26c-fc3685386cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-1&quot;)/div[@class=&quot;pa-av pa-f pa-bj pa-p pa-bk flexbox&quot;]/span[@class=&quot;pa-bl pa-bm&quot;]/span[@class=&quot;symbolFont SiteMap-symbol&quot;]</value>
      <webElementGuid>140bf726-935d-45bb-b1e2-58b63fa84e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='id-1']/div/span/span</value>
      <webElementGuid>cd33bedf-ac90-4ef2-a7a6-058d4caf5502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>55038b2a-ef3d-4734-9e17-f24d7da04e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
