<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>93d17942-16e5-4f44-b846-64053746c7ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='account|NoRelationship|Form|Mscrm.Form.account.Save011-button']/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pa-bz.pa-fd.pa-gs.pa-ao.pa-e.pa-cq.pa-gt.pa-gu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Save (CTRL+S)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eae7901e-9b04-44b6-95eb-77ed2f822c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-bz pa-fd pa-gs pa-ao pa-e pa-cq pa-gt pa-gu </value>
      <webElementGuid>48cc25c9-7bd3-4954-a8ea-76b63a5f6ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>549c178b-49b7-4fdf-80e4-937e174e0ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account|NoRelationship|Form|Mscrm.Form.account.Save011-button&quot;)/span[@class=&quot;pa-ej pa-av pa-a pa-ek&quot;]/span[@class=&quot;pa-bz pa-fd pa-gs pa-ao pa-e pa-cq pa-gt pa-gu&quot;]</value>
      <webElementGuid>b1c442b7-af2a-4ef6-8485-03149c3dc510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='account|NoRelationship|Form|Mscrm.Form.account.Save011-button']/span/span[2]</value>
      <webElementGuid>81cff12a-ba36-400c-b796-d369a2c3f1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last updated at 8:58 PM'])[1]/following::span[4]</value>
      <webElementGuid>8859ef35-b67e-4ab7-a133-1e2f3841fbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[29]/following::span[7]</value>
      <webElementGuid>1474e764-5235-47cd-9c7d-8f11755a50ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save this Company.'])[1]/preceding::span[1]</value>
      <webElementGuid>be7a0abe-6aac-4b11-b7be-33de8218bf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Close'])[1]/preceding::span[3]</value>
      <webElementGuid>41af1196-1564-40e9-b4ff-ef189dbdafb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>587d1dfa-ccc7-4cf2-89ee-21d462c001c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>f6c6f546-02f2-4472-967d-9dca100c61ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>d5e58393-db55-4f33-af22-15ba14979e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='contact|NoRelationship|Form|Mscrm.Form.contact.Save011-button']/span/span[2]</value>
      <webElementGuid>b2256067-59ca-40bd-9d2c-baa08e79e575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last updated at 8:46 PM'])[1]/following::span[4]</value>
      <webElementGuid>97b5402f-7348-48b5-bb3a-43d9a467f6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save this Contact.'])[1]/preceding::span[1]</value>
      <webElementGuid>70285002-45ce-4cd6-a863-525d394e820b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
